test/v0.8/testcases/mocks/core/filecoin/SetMockFilecoinDealStateTestSuite.sol, test/v0.8/testcases/mocks/core/filecoin/abstract/MockFilecoinDealTestBase.sol, test/v0.8/testcases/mocks/core/filecoin/abstract/MockFilecoinDealTestSuiteBase.sol, test/v0.8/uinttests/mocks/core/filecoin/MockFilecoin.t.sol, test/v0.8/uinttests/mocks/core/filecoin/setup/MockFilecoinSetup.sol
=> fix: [#68]

src/v0.8/module/matching/Matchings.sol, test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol, test/v0.8/testcases/module/storage/SubmitStorageDealIdsTestSuite.sol
close #74 
The original code has already implemented this function and the Assertion test item. Here we modify the use part of getMatchingCars.
=> fix: Implement getCars method issue [#74]

src/v0.8/interfaces/module/IStorages.sol, src/v0.8/module/storage/Storages.sol, src/v0.8/service/dataswapstorage/abstract/StoragesService .sol, test/v0.8/assertions/module/storage/StoragesAssertion.sol
=> fix: Implement getCarSize method in storage [#72]

src/v0.8/module/datacap/Datacaps.sol, test/v0.8/testcases/module/datacap/RequestAllocateTestSuite.sol, test/v0.8/uinttests/module/datacap/RequestAllocateDatacap.t.sol
=> fixed: implement datacap exception unit test [#44]

test/v0.8/assertions/module/storage/StoragesAssertion.sol, test/v0.8/testcases/module/storage/SubmitStorageDealIdsTestSuite.sol
=> fix: Implement isAllStoredDoneAssertion test case issue [#73]

test/v0.8/testcases/core/access/AcceptOwnershipTestSuite.sol, test/v0.8/testcases/core/access/CheckRoleTestSuite.sol, test/v0.8/testcases/core/access/GrantRoleTestSuite.sol, test/v0.8/testcases/core/access/RenounceOwnershipTestSuite.sol, test/v0.8/testcases/core/access/RenounceRoleTestSuite.sol, test/v0.8/testcases/core/access/RevokeRoleTestSuite.sol, test/v0.8/testcases/core/access/TransferOwnershipTestSuite.sol, test/v0.8/uinttests/core/access/AcceptOwnership.t.sol, test/v0.8/uinttests/core/access/CheckRole.t.sol, test/v0.8/uinttests/core/access/GrantRole.t.sol, test/v0.8/uinttests/core/access/RenounceOwnership.t.sol, test/v0.8/uinttests/core/access/RenounceRole.t.sol, test/v0.8/uinttests/core/access/RevokeRole.t.sol, test/v0.8/uinttests/core/access/TransferOwnership.t.sol
=> fix: Implement exception test cases access issue [#70]

test/v0.8/testcases/module/dataset/ApproveMetadataTestSuite.sol, test/v0.8/testcases/module/dataset/ApproveTestSuite.sol, test/v0.8/testcases/module/dataset/RejectMetadataTestSuite.sol, test/v0.8/testcases/module/dataset/RejectTestSuite.sol, test/v0.8/testcases/module/dataset/SubmitMetadataTestSuite.sol, test/v0.8/testcases/module/dataset/SubmitProofTestSuite.sol, test/v0.8/testcases/module/dataset/SubmittVerificationTestSuite.sol, test/v0.8/uinttests/module/dataset/Approve.t.sol, test/v0.8/uinttests/module/dataset/ApproveMetadata.t.sol, test/v0.8/uinttests/module/dataset/Reject.t.sol, test/v0.8/uinttests/module/dataset/RejectMetadata.t.sol, test/v0.8/uinttests/module/dataset/SubmitMetadata.t.sol, test/v0.8/uinttests/module/dataset/SubmitProof.t.sol, test/v0.8/uinttests/module/dataset/SubmitVerification.t.sol
=> fix: Implement dataset exception uint test [#42]

src/v0.8/module/dataset/library/challenge/DatasetVerificationLIB.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol
=> fixed: Implement getDatasetVerificationAssertion [#66]

src/v0.8/module/matching/Matchings.sol
=> fixed: implement isMatchingTargetValid [#52]

test/v0.8/testcases/module/storage/SubmitStorageDealIdTestSuite.sol, test/v0.8/testcases/module/storage/SubmitStorageDealIdsTestSuite.sol, test/v0.8/testcases/module/storage/abstract/StoragesTestBase.sol, test/v0.8/uinttests/module/storage/SubmitStorageDealId.t.sol, test/v0.8/uinttests/module/storage/SubmitStorageDealIds.t.sol, test/v0.8/uinttests/module/storage/setup/StorageTestSetup.sol
=> fix: Implement storage unit test[#45]

src/v0.8/module/dataset/Datasets.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/helpers/module/dataset/DatasetsHelpers.sol, test/v0.8/testcases/module/dataset/ApproveMetadataTestSuite.sol, test/v0.8/testcases/module/dataset/ApproveTestSuite.sol, test/v0.8/testcases/module/dataset/RejectMetadataTestSuite.sol, test/v0.8/testcases/module/dataset/RejectTestSuite.sol, test/v0.8/testcases/module/dataset/SubmitProofTestSuite.sol, test/v0.8/testcases/module/dataset/SubmittVerificationTestSuite.sol, test/v0.8/testcases/module/dataset/setup/DatasetsTestSetup.sol
chore: Optimization dataset test code
close #49 
fixed: Add check verification count before dataset audit [#49]
chore: Optimization dataset test code
=> fixed: Add check verification count before dataset audit [#49]

src/v0.8/module/matching/Matchings.sol, test/v0.8/assertions/module/matching/MatchingsAssertion.sol, test/v0.8/helpers/module/matching/MatchingsHelpers.sol, test/v0.8/interfaces/assertions/module/IMatchingsAssertion.sol, test/v0.8/testcases/module/matching/BiddingTestSuite.sol, test/v0.8/testcases/module/matching/CancelTestSuite.sol, test/v0.8/testcases/module/matching/CloseTestSuite.sol, test/v0.8/testcases/module/matching/PauseTestSuite.sol, test/v0.8/testcases/module/matching/PublishMatchingTestSuite.sol, test/v0.8/testcases/module/matching/ResumeTestSuite.sol, test/v0.8/testcases/module/matching/abstract/ControlTestSuiteBase.sol, test/v0.8/uinttests/module/datacap/setup/DatacapTestSetup.sol, test/v0.8/uinttests/module/matching/BiddingMatching.t.sol, test/v0.8/uinttests/module/matching/CancelMatching.t.sol, test/v0.8/uinttests/module/matching/CloseMatching.t.sol, test/v0.8/uinttests/module/matching/PauseMatching.t.sol, test/v0.8/uinttests/module/matching/PublishMatching.t.sol, test/v0.8/uinttests/module/matching/ResumeMatching.t.sol, test/v0.8/uinttests/module/matching/setup/MatchingTestSetup.sol, test/v0.8/uinttests/module/storage/setup/StorageTestSetup.sol
update bidding exception test
update close exception test
update pause exception test
update resume exception test
close #43 
=> fixed: implement matching exception uint test[#43]

src/v0.8/interfaces/module/IDatasets.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/library/proof/DatasetProofInnerLIB.sol, src/v0.8/module/dataset/library/proof/DatasetProofLIB.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/helpers/module/dataset/DatasetsHelpers.sol, test/v0.8/helpers/utils/Generator.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol, test/v0.8/interfaces/helpers/module/IDatasetsHelpers.sol, test/v0.8/testcases/module/dataset/SubmitProofTestSuite.sol, test/v0.8/uinttests/module/dataset/SubmitProof.t.sol
close #64 
close #81 
close #118 
=> fixed: datasets proofs sort leafHashs [#64]

hardhat.config.ts
=> feat: Add getProxyAddress function [#142]

package.json
=> fixed:Prohibit automatic upgrading of OpenZeppelin versions [#144]

.gitignore, README.md, hardhat.config.ts, package.json, scripts/publish_version
=> feat: publish version tools [#146]

src/v0.8/core/carstore/Carstore.sol, src/v0.8/core/finance/Escrow.sol, src/v0.8/interfaces/core/ICarstore.sol, src/v0.8/interfaces/core/IEscrow.sol, src/v0.8/module/datacap/Datacaps.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/matching/MatchingsBids.sol, src/v0.8/module/matching/MatchingsTarget.sol, src/v0.8/module/storage/Storages.sol, src/v0.8/shared/events/EscrowEvents.sol, test/v0.8/assertions/core/carstore/CarstoreAssertion.sol, test/v0.8/assertions/core/escrow/EscrowAssertion.sol, test/v0.8/interfaces/assertions/core/ICarstoreAssertion.sol, test/v0.8/interfaces/assertions/core/IEscrowAssertion.sol, test/v0.8/testcases/core/carstore/AddCarTestSuite.sol, test/v0.8/testcases/core/carstore/RegistCarReplicaTestSuite.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaExpiredTestSuite.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaMatchingStateTestSuite.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaSlashedTestSuite.sol, test/v0.8/testcases/core/carstore/SetCarReplicaFilecoinClaimIdTestSuite.sol, test/v0.8/testcases/core/escrow/CollateralTestSuite.sol, test/v0.8/testcases/core/escrow/PaymentRefundTestSuite.sol, test/v0.8/testcases/core/escrow/PaymentTestSuite.sol, test/v0.8/testcases/core/escrow/PaymentTransferTestSuite.sol, test/v0.8/testcases/core/escrow/PaymentWithdrawTestSuite.sol, test/v0.8/testcases/core/escrow/WithdrawTestSuite.sol
=> feat: Merge related business get interface [#149]

src/v0.8/core/finance/Escrow.sol, src/v0.8/core/finance/library/ConditionalEscrowLIB.sol, src/v0.8/interfaces/module/IDatacaps.sol, src/v0.8/interfaces/module/IDatasets.sol, src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/interfaces/module/IDatasetsProof.sol, src/v0.8/interfaces/module/IMatchings.sol, src/v0.8/interfaces/module/IMatchingsBids.sol, src/v0.8/interfaces/module/IMatchingsTarget.sol, src/v0.8/module/datacap/Datacaps.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/dataset/DatasetsRequirement.sol, src/v0.8/module/matching/Matchings.sol, src/v0.8/module/matching/MatchingsBids.sol, src/v0.8/module/matching/MatchingsTarget.sol, src/v0.8/module/matching/library/MatchingBidsLIB.sol, src/v0.8/module/storage/Storages.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/assertions/module/matching/MatchingsAssertion.sol, test/v0.8/helpers/module/dataset/DatasetsHelpers.sol, test/v0.8/helpers/module/matching/MatchingsHelpers.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol, test/v0.8/testcases/core/escrow/PaymentRefundTestSuite.sol, test/v0.8/testcases/module/storage/SubmitStorageClaimIdTestSuite.sol, test/v0.8/testcases/module/storage/SubmitStorageClaimIdsTestSuite.sol, test/v0.8/uinttests/helpers/BaseTestSetup.sol
=> fixed: Merge get interface of Datacaps, Datasets, Matchings, Storages

src/v0.8/core/access/Roles.sol, src/v0.8/core/carstore/Carstore.sol, src/v0.8/core/carstore/abstract/CarstoreBase.sol, src/v0.8/core/filecoin/Filecoin.sol, src/v0.8/core/finance/Escrow.sol, src/v0.8/interfaces/core/ICarstore.sol, src/v0.8/interfaces/core/IFilecoin.sol, src/v0.8/interfaces/core/IRoles.sol, src/v0.8/interfaces/module/IMatchings.sol, src/v0.8/mocks/core/filecoin/MockFilecoin.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/matching/Matchings.sol, src/v0.8/shared/errors/Errors.sol, src/v0.8/shared/modifiers/MatchingsModifiers.sol, src/v0.8/types/RolesType.sol, test/v0.8/assertions/core/carstore/CarstoreAssertion.sol, test/v0.8/interfaces/assertions/core/ICarstoreAssertion.sol, test/v0.8/testcases/core/carstore/AddCarTestSuite.sol, test/v0.8/testcases/core/carstore/AddCarsTestSuite.sol, test/v0.8/testcases/core/carstore/RegistCarReplicaTestSuite.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaExpiredTestSuite.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaMatchingStateTestSuite.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaSlashedTestSuite.sol, test/v0.8/testcases/core/carstore/SetCarReplicaFilecoinClaimIdTestSuite.sol, test/v0.8/testcases/core/carstore/abstract/CarstoreTestSuiteBase.sol, test/v0.8/testcases/core/escrow/PaymentRefundTestSuite.sol, test/v0.8/testcases/core/escrow/PaymentWithdrawTestSuite.sol, test/v0.8/uinttests/helpers/BaseTestSetup.sol
feat: Add interface permission control for Datasets Matchings and Filecoin
fixed: Modify test error
fixed: Modify escrow test ok
fixed: Modify test error of carstore
close #7 #132 
=> feat: Add interface permission control between internal contracts

package.json, scripts/publish_version
=> update version to 0.1.2

scripts/localnet_docker/Dockerfile, scripts/localnet_docker/build.sh, scripts/localnet_docker/devnet-entry.bash, scripts/localnet_docker/devnet.bash, scripts/localnet_docker/devnet.patch
=> feat: add docker file [ #156 ]

package.json, src/v0.8/core/carstore/Carstore.sol, src/v0.8/core/finance/Escrow.sol, src/v0.8/interfaces/core/ICarstore.sol, src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/interfaces/module/IDatasetsRequirement.sol, src/v0.8/interfaces/module/IMatchingsBids.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsRequirement.sol, src/v0.8/module/dataset/library/challenge/DatasetChallengeProofLIB.sol, src/v0.8/module/dataset/library/requirement/DatasetReplicaRequirementLIB.sol, src/v0.8/module/matching/MatchingsBids.sol
=> feat: Add function returns name tag#158

.github/CODE_OF_CONDUCT.md, .release-it.json, CONTRIBUTING.md, LICENSE, README.md, package.json, templates/readme.md
=> docs: ✏️ Unified Document Style

src/v0.8/module/matching/MatchingsBids.sol
=> fix: 🐛 Bidding payment support HighestBid and ImmediateAtLeast

scripts/localnet_docker/devnet.bash
=> fix: 🐛 Increase notary datacap capacity in docker image

src/v0.8/types/MatchingType.sol
=> chore: 🤖 Add matching subsidy paramter comment #181

src/v0.8/interfaces/module/IDatasetsProof.sol, src/v0.8/module/dataset/DatasetsProof.sol
=> fix: 🐛 Add return state for submitDatasetProofCompleted

src/v0.8/core/statistics/StatisticsBase.sol, src/v0.8/core/statistics/StorageStatisticsBase.sol, src/v0.8/core/statistics/library/StatisticsLIB.sol, src/v0.8/core/statistics/library/StorageProvidersStatisticsLIB.sol, src/v0.8/core/statistics/library/StorageStatisticsLIB.sol, src/v0.8/interfaces/core/statistics/IStatistics.sol, src/v0.8/interfaces/core/statistics/IStorageStatistics.sol, src/v0.8/interfaces/module/IDatasets.sol, src/v0.8/interfaces/module/IMatchings.sol, src/v0.8/interfaces/module/IStorages.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/matching/Matchings.sol, src/v0.8/module/storage/Storages.sol, src/v0.8/types/StatisticsType.sol
=> feat: 🎸 add statistic lib

src/v0.8/core/statistics/StatisticsBase.sol, test/v0.8/assertions/core/statistics/StatisticsBaseAssertion.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/interfaces/assertions/core/IStatisticsBaseAssertion.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol
=> feat: 🎸 complete universal statistics base

src/v0.8/core/statistics/StorageStatisticsBase.sol, src/v0.8/interfaces/core/statistics/IStorageStatistics.sol, src/v0.8/module/storage/Storages.sol, test/v0.8/assertions/core/statistics/StorageStatisticsBaseAssertion.sol, test/v0.8/interfaces/assertions/core/IStorageStatisticsBaseAssertion.sol
=> feat: 🎸 complete storage statistics base

src/v0.8/core/access/Roles.sol, src/v0.8/types/RolesType.sol
=> feat: 🎸 Add unified contract management function

src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/shared/utils/array/ArrayLIB.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol
=> feat: 🎸 add getDatasetChallengeProofsSubmitter method

src/v0.8/interfaces/core/IFinance.sol, src/v0.8/types/FinanceType.sol
✅ Closes: #226
✅ Closes: #204 
close
=> feat: 🎸 Update finance interface

src/v0.8/core/access/Roles.sol, src/v0.8/core/finance/Escrow.sol, src/v0.8/core/finance/library/ConditionalEscrowLIB.sol, src/v0.8/interfaces/core/IRoles.sol, src/v0.8/interfaces/module/IDatasets.sol, src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/interfaces/module/IDatasetsProof.sol, src/v0.8/interfaces/module/IDatasetsRequirement.sol, src/v0.8/interfaces/module/IMatchings.sol, src/v0.8/interfaces/module/IMatchingsBids.sol, src/v0.8/interfaces/module/IMatchingsTarget.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/dataset/DatasetsRequirement.sol, src/v0.8/module/matching/Matchings.sol, src/v0.8/module/matching/MatchingsBids.sol, src/v0.8/module/matching/MatchingsTarget.sol, src/v0.8/types/RolesType.sol, test/v0.8/testcases/module/dataset/SubmittChallengeProofsTestSuite.sol, test/v0.8/uinttests/helpers/BaseTestSetup.sol
=> feat: 🎸 Modify dependent contract in the business contract

src/v0.8/interfaces/core/statistics/IStorageStatistics.sol, src/v0.8/interfaces/module/IStorages.sol, src/v0.8/module/storage/Storages.sol, test/v0.8/assertions/module/storage/StoragesAssertion.sol, test/v0.8/helpers/module/storage/StoragesHelpers.sol, test/v0.8/interfaces/assertions/module/IStoragesAssertion.sol, test/v0.8/testcases/core/escrow/PaymentRefundTestSuite.sol, test/v0.8/testcases/module/storage/RequestAllocateTestSuite.sol, test/v0.8/testcases/module/storage/SubmitStorageClaimIdTestSuite.sol, test/v0.8/testcases/module/storage/SubmitStorageClaimIdsTestSuite.sol, test/v0.8/uinttests/helpers/BaseTestSetup.sol
=> feat: 🎸 upate interface dependent contract of storage

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/finance/library/DatacapCollateralLIB.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/shared/events/FilplusEvents.sol
=> feat: 🎸 Design EscrowLibrary Model（DatacapCollateral)

src/v0.8/core/finance/Finance.sol, src/v0.8/core/finance/library/ChallengeCommissionLIB.sol, src/v0.8/core/finance/library/DataTradingFeeLIB.sol, src/v0.8/core/finance/library/DatacapChunkLandLIB.sol, src/v0.8/core/finance/library/DatacapCollateralLIB.sol, src/v0.8/interfaces/core/IFinance.sol
=> feat: 🎸 Finance add isEscrowEnough interface #252

src/v0.8/core/carstore/Carstore.sol, src/v0.8/core/carstore/abstract/CarstoreBase.sol, src/v0.8/interfaces/core/ICarstore.sol, test/v0.8/assertions/core/carstore/CarstoreAssertion.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaExpiredTestSuite.sol, test/v0.8/testcases/core/carstore/ReportCarReplicaSlashedTestSuite.sol, test/v0.8/uinttests/core/carstore/SetCarReplicaFilecoinClaimId.t.sol, test/v0.8/uinttests/helpers/BaseTestSetup.sol
=> fix: 🐛 Remove the IFilplus and IFilecoin from carstore

src/v0.8/core/filplus/Filplus.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/shared/events/FilplusEvents.sol, src/v0.8/types/FilplusType.sol
=> feat: 🎸 Optimize Filplus rules, define types of filplus rules

src/v0.8/interfaces/module/IMatchingsTarget.sol, src/v0.8/module/matching/MatchingsTarget.sol, src/v0.8/shared/utils/array/ArrayLIB.sol, test/v0.8/assertions/module/matching/MatchingsAssertion.sol, test/v0.8/interfaces/assertions/module/IMatchingsAssertion.sol
=> fix: 🐛 Remove the 'parseCars' function from 'matchingTarget'

src/v0.8/core/statistics/BusnessFinanceStatistics.sol, src/v0.8/core/statistics/StatisticsBase.sol, src/v0.8/core/statistics/StorageStatisticsBase.sol, src/v0.8/core/statistics/library/FinanceStatisticsLIB.sol, src/v0.8/interfaces/core/statistics/IBusinessFinanceStatistics.sol, src/v0.8/interfaces/core/statistics/IMemberFinanceStatistics.sol, src/v0.8/types/StatisticsType.sol
=> feat: 🎸 finance statistics

src/v0.8/interfaces/module/IDatasets.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/matching/MatchingsTarget.sol, src/v0.8/types/DatasetType.sol
=> fix: 🐛 Remove Datasets contract addDatasetUsedSize interface

deploy/05_deploy_escrowdatacapcollateral.ts, deploy/06_deploy_escrowdatatradingfee.ts, deploy/07_deploy_escrowdatacapchunklandcollateral.ts, deploy/08_deploy_escrowchallengecommission.ts, src/v0.8/core/access/Roles.sol, src/v0.8/core/finance/Finance.sol, src/v0.8/core/finance/escrow/EscrowBase.sol, src/v0.8/core/finance/escrow/EscrowChallengeCommission.sol, src/v0.8/core/finance/escrow/EscrowDataTradingFee.sol, src/v0.8/core/finance/escrow/EscrowDatacapChunkLandCollateral.sol, src/v0.8/core/finance/escrow/EscrowDatacapCollateral.sol, src/v0.8/core/finance/library/FinanceAccountLIB.sol, src/v0.8/interfaces/core/IEscrow.sol, src/v0.8/interfaces/core/IFinance.sol, src/v0.8/interfaces/core/IRoles.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/dataset/DatasetsRequirement.sol, src/v0.8/module/matching/MatchingsBids.sol, src/v0.8/module/storage/Storages.sol, src/v0.8/shared/errors/Errors.sol, src/v0.8/shared/events/FinanceEvents.sol, src/v0.8/shared/modifiers/FinanceModifiers.sol, src/v0.8/types/FinanceType.sol, src/v0.8/types/RolesType.sol
✅ Closes: #244 
✅ Closes: #245
✅ Closes: #258 
=> feat: 🎸 Add finance base library interface implementation

src/v0.8/core/finance/Finance.sol, src/v0.8/core/finance/escrow/EscrowBase.sol, src/v0.8/core/finance/escrow/EscrowChallengeCommission.sol, src/v0.8/core/finance/escrow/EscrowDataTradingFee.sol, src/v0.8/core/finance/escrow/EscrowDatacapChunkLandCollateral.sol, src/v0.8/core/finance/escrow/EscrowDatacapCollateral.sol, src/v0.8/interfaces/core/IEscrow.sol, src/v0.8/interfaces/core/IFinance.sol, src/v0.8/interfaces/module/IMatchingsTarget.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/dataset/DatasetsRequirement.sol, src/v0.8/module/matching/MatchingsBids.sol, src/v0.8/module/matching/MatchingsTarget.sol, src/v0.8/module/matching/library/MatchingTargetLIB.sol, src/v0.8/module/storage/Storages.sol, src/v0.8/types/FinanceType.sol, src/v0.8/types/MatchingType.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/assertions/module/matching/MatchingsAssertion.sol, test/v0.8/assertions/module/storage/StoragesAssertion.sol, test/v0.8/helpers/module/dataset/DatasetsHelpers.sol, test/v0.8/testcases/module/dataset/setup/DatasetsTestSetup.sol, test/v0.8/testcases/module/storage/SubmitStorageClaimIdTestSuite.sol, test/v0.8/testcases/module/storage/SubmitStorageClaimIdsTestSuite.sol, test/v0.8/uinttests/helpers/BaseTestSetup.sol
=> feat: 🎸 Modify subsidy update mechanism

src/v0.8/core/carstore/Carstore.sol, src/v0.8/core/carstore/library/CarLIB.sol, src/v0.8/interfaces/core/ICarstore.sol, src/v0.8/interfaces/module/IDatasets.sol, src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/interfaces/module/IDatasetsProof.sol, src/v0.8/interfaces/module/IDatasetsRequirement.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/dataset/DatasetsRequirement.sol, src/v0.8/module/dataset/library/metadata/DatasetMetadataLIB.sol, src/v0.8/module/dataset/library/requirement/DatasetReplicaRequirementLIB.sol, src/v0.8/shared/errors/Errors.sol, src/v0.8/shared/modifiers/DatasetsModifiers.sol, test/v0.8/assertions/core/carstore/CarstoreAssertion.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/helpers/module/dataset/DatasetsHelpers.sol, test/v0.8/interfaces/assertions/core/ICarstoreAssertion.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol, test/v0.8/interfaces/helpers/module/IDatasetsHelpers.sol, test/v0.8/testcases/module/dataset/SubmitMetadataTestSuite.sol, test/v0.8/testcases/module/dataset/SubmitProofTestSuite.sol, test/v0.8/testcases/module/dataset/SubmitReplicaRequirementsTestSuite.sol, test/v0.8/testcases/module/dataset/SubmittChallengeProofsTestSuite.sol, test/v0.8/testcases/module/dataset/setup/DatasetsTestSetup.sol, test/v0.8/uinttests/module/dataset/SubmitChallengeProof.t.sol, test/v0.8/uinttests/module/dataset/SubmitProof.t.sol, test/v0.8/uinttests/module/dataset/SubmitReplicaRequirements.t.sol
=> feat: 🎸 Implement the business overtime of dataset

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/finance/Finance.sol, src/v0.8/core/finance/escrow/EscrowBase.sol, src/v0.8/core/finance/escrow/EscrowChallengeCommission.sol, src/v0.8/core/finance/escrow/EscrowDataTradingFee.sol, src/v0.8/core/finance/escrow/EscrowDatacapCollateral.sol, src/v0.8/interfaces/core/IEscrow.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/interfaces/core/IFinance.sol, src/v0.8/module/matching/MatchingsBids.sol, src/v0.8/shared/events/FilplusEvents.sol, src/v0.8/types/FilplusType.sol, test/v0.8/assertions/core/finance/FinanceAssertion.sol, test/v0.8/interfaces/assertions/core/IFinanceAssertion.sol, test/v0.8/testcases/core/finance/DepositTestSuite.sol, test/v0.8/testcases/core/finance/EscrowTestSuite.sol, test/v0.8/testcases/core/finance/WithdrawTestSuit.sol, test/v0.8/testcases/core/finance/__EscrowTestSuite.sol, test/v0.8/testcases/core/finance/abstract/FinanceTestBase.sol, test/v0.8/testcases/core/finance/abstract/FinanceTestSuiteBase.sol, test/v0.8/types/FinanceTestType.sol, test/v0.8/uinttests/core/finance/Deposit.t.sol, test/v0.8/uinttests/core/finance/Withdraw.t.sol, test/v0.8/uinttests/core/finance/__Escrow.t.sol, test/v0.8/uinttests/core/finance/setup/FinanceTestSetup.sol
=> feat: 🎸 Add finance test code

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/finance/escrow/EscrowProofAuditCollateral.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/shared/events/FilplusEvents.sol, src/v0.8/types/FilplusType.sol
=> feat: 🎸 Implement ProofAudit escrow contract

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/finance/escrow/EscrowChallengeAuditCollateral.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/shared/events/FilplusEvents.sol, src/v0.8/types/FilplusType.sol
=> feat: 🎸 Implement ChallengeAudit escrow contract

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/finance/escrow/EscrowDisputeAuditCollateral.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/shared/events/FilplusEvents.sol, src/v0.8/types/FilplusType.sol
=> feat: 🎸 Implement DisputeAudit escrow contract

scripts/localnet_docker/devnet.bash
=> feat: 🎸 update devnet.bash

src/v0.8/interfaces/core/IFinance.sol
=> fix: 🐛 getAccountEscrow interface Arguments in wrong order

src/v0.8/core/statistics/BusinessFinanceStatistics.sol, src/v0.8/interfaces/core/statistics/IBusinessFinanceStatistics.sol, src/v0.8/types/StatisticsType.sol
=> fix: 🐛 change tvl to escrow in statistics

src/v0.8/core/statistics/BusinessFinanceStatistics.sol, src/v0.8/interfaces/core/statistics/IBusinessFinanceStatistics.sol, src/v0.8/types/StatisticsType.sol
=> feat: 🎸 Add StorageProviderDatacapChunkLandPenalty to statistic

scripts/localnet_docker/build.sh, scripts/localnet_docker/devnet.bash
=> fix: 🐛 Initialization after contract deployment in the docker

src/v0.8/core/finance/Finance.sol, src/v0.8/core/finance/escrow/EscrowBase.sol, src/v0.8/core/finance/escrow/EscrowChallengeAuditCollateral.sol, src/v0.8/core/finance/escrow/EscrowChallengeCommission.sol, src/v0.8/core/finance/escrow/EscrowDataTradingFee.sol, src/v0.8/core/finance/escrow/EscrowDatacapChunkLandCollateral.sol, src/v0.8/core/finance/escrow/EscrowDatacapCollateral.sol, src/v0.8/core/finance/escrow/EscrowDisputeAuditCollateral.sol, src/v0.8/core/finance/escrow/EscrowProofAuditCollateral.sol, src/v0.8/interfaces/core/IEscrow.sol, test/v0.8/uinttests/helpers/BaseTestSetup.sol
=> feat: 🎸 Modify the IEScrowBase extend interface as the internal

scripts/localnet_docker/devnet.bash, src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/library/challenge/DatasetChallengeProofLIB.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol
=> fix: 🐛 Fixed the issue with submitDatasetChallengeProofs

src/v0.8/module/dataset/DatasetsChallenge.sol
=> fix: 🐛 fix submitDatasetChallengeProofs

scripts/contract_initialization.ts
=> feat: 🎸 Add contract initialization function 

src/v0.8/core/finance/escrow/EscrowDataTradingFee.sol
=> fix: 🐛 Add support for obtaining subsidy requirements

hardhat.config.ts, package.json, scripts/contract_initialization.ts, scripts/utils.ts
=> fix: 🐛 Fix contract upgrade issue

src/v0.8/core/statistics/StorageStatisticsBase.sol, test/v0.8/assertions/module/matching/MatchingsAssertion.sol
=> fix: 🐛 fix matching storage statistics

deploy/02_deploy_filplus.ts, deploy/11_deploy_dataset.ts, deploy/12_deploy_datasetsrequirement.ts, deploy/13_deploy_datasetsproof.ts, deploy/14_deploy_datasetschallenge.ts, deploy/15_deploy_matchings.ts, deploy/16_deploy_matchingstarget.ts, deploy/17_deploy_matchingsbids.ts, deploy/18_deploy_storages.ts, hardhat.config.ts, scripts/constants.ts, scripts/contract_initialization.ts, scripts/localnet_docker/devnet.bash
=> fix: 🐛 Improve the configuration of the deployment tool

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/finance/escrow/EscrowChallengeAuditCollateral.sol, src/v0.8/core/finance/escrow/EscrowChallengeCommission.sol, src/v0.8/core/finance/escrow/EscrowDatacapChunkLandCollateral.sol, src/v0.8/core/finance/escrow/EscrowDatacapCollateral.sol, src/v0.8/core/finance/escrow/EscrowDisputeAuditCollateral.sol, src/v0.8/core/finance/escrow/EscrowProofAuditCollateral.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/library/challenge/DatasetAuditorElectionLIB.sol, src/v0.8/module/storage/Storages.sol, src/v0.8/shared/events/FilplusEvents.sol, src/v0.8/types/FilplusType.sol, test/v0.8/assertions/core/filplus/FilplusAssertion.sol, test/v0.8/testcases/core/filplus/SetDatacapRuleMaxAllocatedSizePerTimeTestSuite.sol, test/v0.8/testcases/core/filplus/SetDatacapRuleMaxRemainingPercentageForNextTestSuite.sol, test/v0.8/uinttests/core/filplus/SetDatacapRuleMaxAllocatedSizePerTime.t.sol, test/v0.8/uinttests/core/filplus/SetDatacapRuleMaxRemainingPercentageForNext.t.sol
rename: datacapRuleMaxAllocatedSizePerTime datacapRuleMaxAllocatedSizePerTime datacapRuleMaxRemainingPercentageForNext datacapPricePreByte datacapChunkLandPricePreByte challengeProofsPricePrePoint challengeProofsPricePrePoint datacapdatasetApprovedLockDays datacapCollateralMaxLockDays and proofAuditFee challengeAuditFee disputeAuditFee
✅ Closes: #351 
close
=> fix: 🐛 renaming of filplus rules

src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/library/challenge/DatasetAuditorElectionLIB.sol, test/v0.8/helpers/module/dataset/DatasetsHelpers.sol, test/v0.8/testcases/module/dataset/SubmittChallengeProofsTestSuite.sol, test/v0.8/testcases/module/dataset/setup/DatasetsTestSetup.sol
=> fix: 🐛 remove getChallengeAuditCollateralRequirement

src/v0.8/interfaces/module/IDatasetsProof.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/dataset/library/proof/DatasetProofLIB.sol
(update datasetProof contract) add function getDatasetProofRootHash
✅ Closes: #354
close
=> fix: 🐛 add func getDatasetProofRootHash

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/statistics/StatisticsBase.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/shared/events/StatisticsEvents.sol
(update contract datasets ,matchings,storages)
✅ Closes: #356
close
=> fix: 🐛 merge count and size statistics

src/v0.8/core/statistics/StatisticsBase.sol, src/v0.8/core/statistics/StorageStatisticsBase.sol, src/v0.8/module/dataset/Datasets.sol, src/v0.8/module/matching/Matchings.sol, src/v0.8/shared/events/StatisticsEvents.sol, src/v0.8/types/StatisticsType.sol
=> fix: 🐛 fix statistics events

src/v0.8/core/filecoin/Filecoin.sol
Resolving the issue of incorrect CID length obtained from the claim.
✅ Closes: #366
close
=> fix: 🐛 Resolving the issue of incorrect CID length

src/v0.8/module/matching/library/MatchingBidsLIB.sol
=> fix: 🐛 remove import of SendAPI from matchingBids

src/v0.8/core/filplus/Filplus.sol, src/v0.8/core/finance/escrow/EscrowChallengeCommission.sol, src/v0.8/interfaces/core/IFilplus.sol, src/v0.8/interfaces/module/IDatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/library/challenge/DatasetChallengeProofLIB.sol, src/v0.8/shared/events/FilplusEvents.sol, src/v0.8/types/FilplusType.sol, test/v0.8/assertions/module/dataset/DatasetsAssertion.sol, test/v0.8/helpers/module/dataset/DatasetsHelpers.sol, test/v0.8/interfaces/assertions/module/IDatasetsAssertion.sol, test/v0.8/testcases/module/dataset/SubmittChallengeProofsTestSuite.sol
=> fix: 🐛 “Challenge proof" logical organization submission

src/v0.8/interfaces/module/IDatasetsProof.sol, src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/DatasetsProof.sol, src/v0.8/module/dataset/library/proof/DatasetProofLIB.sol, src/v0.8/types/DatasetType.sol
=> fix: 🐛 update _getSecureDatasetChallengePoints

scripts/localnet_docker/Dockerfile, scripts/localnet_docker/devnet-entry.bash, scripts/localnet_docker/devnet.bash, scripts/localnet_docker/devnet.patch
=> fix: 🐛 update docker scripts

src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/library/challenge/DatasetChallengeProofLIB.sol
=> fix: 🐛 fix generateChallengeIndex

src/v0.8/module/dataset/DatasetsChallenge.sol, src/v0.8/module/dataset/library/challenge/DatasetChallengeProofLIB.sol
=> fix: 🐛 Fixed _getChallengeRoots function
